# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

# default constants
CONFIGFILE_HOSTS = 'file_config.json'

file = File.open CONFIGFILE_HOSTS
data = JSON.load file
file.close

Vagrant.configure(2) do |config|
    data.each do |machine|
        config.vm.define machine["hostname"] do |node|
            node.vm.box = machine["box"]
            node.vm.hostname = machine["hostname"]
            node.vm.network 'private_network', ip: machine["ip"]
            node.vm.provider 'virtualbox' do |vb|
                vb.customize ['modifyvm', :id, '--memory', machine["ram"]]
                vb.customize ['modifyvm', :id, '--cpus', machine["cpu"]]
            end
        end
    end
end
